# Store Type creation script using Invoke-RestMethod
# Generated by Doctool

# Configuration - set these variables before running
$KeyfactorHostname = $env:KEYFACTOR_HOSTNAME
$KeyfactorApiPath = if ($env:KEYFACTOR_API_PATH) { $env:KEYFACTOR_API_PATH } else { "KeyfactorAPI" }
$KeyfactorAuthToken = $env:KEYFACTOR_AUTH_TOKEN

$Headers = @{
    "Authorization" = "Bearer $KeyfactorAuthToken"
    "Content-Type" = "application/json"
    "x-keyfactor-requested-with" = "APIClient"
}

Write-Host "Creating store type: DataPower"
$Body = @'
{
  "Name": "IBM Data Power",
  "ShortName": "DataPower",
  "Capability": "DataPower",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": true,
    "Enrollment": false,
    "Remove": false
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "Api UserName for DataPower. (or valid PAM key if the username is stored in a KF Command configured PAM integration)."
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "A password for DataPower API access.  Used for inventory.(or valid PAM key if the password is stored in a KF Command configured PAM integration)."
    },
    {
      "Name": "ServerUseSsl",
      "DisplayName": "Use SSL",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "true",
      "Required": true,
      "Description": "Should be true, http is not supported."
    },
    {
      "Name": "InventoryBlackList",
      "DisplayName": "Inventory Black List",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": false,
      "Description": "Comma seperated list of alias values you do not want to inventory from DataPower."
    },
    {
      "Name": "Protocol",
      "DisplayName": "Protocol Name",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "https",
      "Required": true,
      "IsPAMEligible": false,
      "Description": "Comma seperated list of alias values you do not want to inventory from DataPower."
    },
    {
      "Name": "PublicCertStoreName",
      "DisplayName": "Public Cert Store Name",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "pubcert",
      "Required": true,
      "IsPAMEligible": false,
      "Description": "This probably will remain pubcert unless someone changed the default name in DataPower."
    },
    {
      "Name": "InventoryPageSize",
      "DisplayName": "Inventory Page Size",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "100",
      "Required": true,
      "IsPAMEligible": false,
      "Description": "This determines the page size during the inventory calls. (100 should be fine)."
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

